"""Initial migration

Revision ID: 5d6ca2341608
Revises: 
Create Date: 2024-09-25 19:31:57.255385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d6ca2341608'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('points_of_sale',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_points_of_sale_id'), 'points_of_sale', ['id'], unique=False)
    op.create_index(op.f('ix_points_of_sale_location'), 'points_of_sale', ['location'], unique=False)
    op.create_index(op.f('ix_points_of_sale_name'), 'points_of_sale', ['name'], unique=False)
    op.create_table('taste',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('cost_by_gr', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_taste_description'), 'taste', ['description'], unique=False)
    op.create_index(op.f('ix_taste_id'), 'taste', ['id'], unique=False)
    op.create_index(op.f('ix_taste_name'), 'taste', ['name'], unique=False)
    op.create_table('popcorns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('taste_id', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['taste_id'], ['taste.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_popcorns_created_on'), 'popcorns', ['created_on'], unique=False)
    op.create_index(op.f('ix_popcorns_id'), 'popcorns', ['id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_date', sa.DateTime(), nullable=True),
    sa.Column('popcorn_id', sa.Integer(), nullable=True),
    sa.Column('point_of_sale_id', sa.Integer(), nullable=True),
    sa.Column('total_price', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['point_of_sale_id'], ['points_of_sale.id'], ),
    sa.ForeignKeyConstraint(['popcorn_id'], ['popcorns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_index(op.f('ix_orders_order_date'), 'orders', ['order_date'], unique=False)
    op.create_table('production',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('production_date', sa.DateTime(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('popcorn_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['popcorn_id'], ['popcorns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_production_id'), 'production', ['id'], unique=False)
    op.create_index(op.f('ix_production_production_date'), 'production', ['production_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_production_production_date'), table_name='production')
    op.drop_index(op.f('ix_production_id'), table_name='production')
    op.drop_table('production')
    op.drop_index(op.f('ix_orders_order_date'), table_name='orders')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_popcorns_id'), table_name='popcorns')
    op.drop_index(op.f('ix_popcorns_created_on'), table_name='popcorns')
    op.drop_table('popcorns')
    op.drop_index(op.f('ix_taste_name'), table_name='taste')
    op.drop_index(op.f('ix_taste_id'), table_name='taste')
    op.drop_index(op.f('ix_taste_description'), table_name='taste')
    op.drop_table('taste')
    op.drop_index(op.f('ix_points_of_sale_name'), table_name='points_of_sale')
    op.drop_index(op.f('ix_points_of_sale_location'), table_name='points_of_sale')
    op.drop_index(op.f('ix_points_of_sale_id'), table_name='points_of_sale')
    op.drop_table('points_of_sale')
    # ### end Alembic commands ###
